sudo: required
services:
  - docker

before_install:
  - docker build -t mgregoire/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mgregoire/react-test npm test

after_success:
  - docker build -t mgregoire/multi-client ./client
  - docker build -t mgregoire/multi-nginx ./nginx
  - docker build -t mgregoire/multi-server ./server
  - docker build -t mgregoire/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" "--password-stdin"
  - docker push mgregoire/multi-client
  - docker push mgregoire/multi-nginx
  - docker push mgregoire/multi-server
  - docker push mgregoire/multi-worker
